[package]
name = "file-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.34"
clap = { version = "3.1.9", features = ["derive"] }
tracing-subscriber = "0.3.11"
walkdir = "2"
